# Project
version=3.3.0
group=org.infernalstudios.questlog
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Questlog
mod_author=Infernal Studios
mod_id=questlog
license=Apache-2.0
credits=Designed by Nekomaster1000 and developed by SwanX1 & evanbones
description=Questlog is a mod that adds a questing system to Minecraft! Quests are written and added via config. Check out the GitHub for info on the syntax, and the Infernal Studios website for the config generator!
minecraft_version_range=[1.21.1, 1.21.2)

# Parchment
neo_form_version=1.21.1-20240808.144430
parchment_minecraft=1.21
parchment_version=2024.11.10

# Optional Dependencies
cloth_config_version=15.0.140
mod_menu_version=11.0.3
emi_version=1.1.22+1.21.1
triggers_version=1.0.1-1.21.1
origins_neoforge_version=0.2.1
origins_fabric_version=1.13.0-pre.2+mc.1.21.1
jupiter_version=2.3.7-1.21.1

# Fabric
fabric_version=0.116.6+1.21.1
fabric_loader_version=0.16.9

# NeoForge
neoforge_version=21.1.228
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.vfs.watch=true